language: node_js
node_js:
  - 14
script:
  - pnpm run lint
  - pnpm run test
  - pnpm run build
  - nyc --silent pnpm run test
  # - nyc report --reporter=text-lcov | coveralls
  # - nyc check-coverage --lines 30
after_success:
  - NODE_ENV=production pnpm run build
  - semantic-release
notifications:
  email: false
sudo: false
